version: '3.8'

volumes:
  static_value:
  media_value:
  database:

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: themasterid/yamdb_final:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.0
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
